# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "sr_mod"
    "bcache"
    "nvme"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  hardware.cpu.intel.updateMicrocode = true;
  boot.kernel.sysctl."net.ipv4.ip_forward" = 1;
  boot.kernel.sysctl."net.ipv6.conf.all.forwarding" = 1;

  boot.initrd.secrets = {
    "/etc/diskkey" = "/etc/nixos/key";
  };

  boot.initrd.luks.devices = {
    root = {
      device = "/dev/disk/by-uuid/f692ec25-2ad3-487b-b1f4-e103a6301dd6";
      preLVM = true;
      allowDiscards = true;
      keyFile = "/etc/diskkey";
    };
    s1 = {
      device = "/dev/disk/by-uuid/ff52bdf7-08a7-45b7-acfd-3cb736bbacf8";
      preLVM = true;
      keyFile = "/etc/diskkey";
    };
    s2 = {
      device = "/dev/disk/by-uuid/023921ee-2630-49d7-b7e8-e25db57e434b";
      preLVM = true;
      keyFile = "/etc/diskkey";
    };
    s3 = {
      device = "/dev/disk/by-uuid/94ba2d51-7942-46a3-bb17-c4cefa75680a";
      preLVM = true;
      keyFile = "/etc/diskkey";
    };
    s4 = {
      device = "/dev/disk/by-uuid/533ad7ce-03be-4507-a2d0-6b362fc599f3";
      preLVM = true;
      keyFile = "/etc/diskkey";
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/82fdf77e-d246-4a10-ba67-68d4478b4261";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  fileSystems."/mnt/s" =
    {
      device = "/dev/mapper/s1:/dev/mapper/s2:/dev/mapper/s3:/dev/mapper/s4";
      fsType = "bcachefs";
    };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C123-4B30";
    fsType = "vfat";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/c86be398-fbd8-4468-928a-df420202ffac"; } ];

  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver
      vaapiIntel
      vaapiVdpau
      libvdpau-va-gl
      intel-compute-runtime # OpenCL filter support (hardware tonemapping and subtitle burn-in)
    ];
  };

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
